config/routes.rb
Rails.application.routes.draw do
  get 'users/edit'

  get 'users/show'

 devise_for :users
 resources :users, only: [:show, :edit, :update]
 resources :posts do
 	resource :favorites, only: [:create, :destroy]
 end

 root 'posts#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user

	has_many :favorites, dependent: :destroy

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :favorites, dependent: :destroy

  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  add_flash_types :success, :info, :warning, :danger


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	before_action :authenticate_user!

	def create
		post = Post.find(params[:post_id])
		favorite = current_user.favorites.new(post_id: post.id)
		favorite.save
		redirect_to post_path(id: post.id), success: 'ふぁぼりました!'
	end

	def destroy
		favorite = current_user.favorites.find_by(post_id: params[:post_id])
		favorite.destroy
		redirect_to post_path(id: favorite.post_id)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def new
  	@post = Post.new
  end

  def create
  	post = Post.new(post_params)
    post.user_id = current_user.id
  	post.save
  	redirect_to '/posts'
  end

  def index
  	@posts = Post.all.reverse_order
    @post = Post.new
    @counta = Post.where(user_id: current_user)
    @countb = Favorite.where(user_id: current_user)
    @users = User.all
    @user = User.find(current_user.id)
  end

  def show
  	@post = Post.find(params[:id])
    @posta = Post.new
    @user = User.find_by(id: @post.user_id)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to '/posts'
  end

  def destroy
    @post_d = Post.find(params[:id])
    @post_d.destroy
    redirect_to posts_path
  end


  private

    def post_params
  	  params.require(:post).permit(:content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def show
  	@user = User.find(params[:id])
  	@posts = Post.where(user_id: params[:id]).reverse_order
  	@favorites = Favorite.where(user_id: params[:id])
  end

  def edit
  	@user = User.find(current_user.id)
  	@posts = Post.where(user_id: current_user.id)
  	@favorites = Favorite.where(user_id: current_user.id)
  end

  def update
  	@user = User.find(current_user.id)
  	@user.update(user_params)
  	redirect_to user_path(current_user.id)
  end

private
	def user_params
	 params.require(:user).permit(:name, :profile, :profile_image)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tsubuyaki</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<header class="navbar navbar-fixed-top">
    <% if user_signed_in?%>
      <div class="row">
        <div class="col-lg-offset-1 col-lg-4">
          <div class="row">
            <a href="/posts">
            <div class="col-lg-3">
              <p class="menu_content menu_hover">
                <i class="fas fa-home"></i> Home
              </p>
            </div>
            </a>
            <a href="#">
            <%= link_to user_path(current_user.id) do %>
            <div class="col-lg-3">
              <p class="menu_content menu_hover">
                <i class="fas fa-user"></i> You
              </p>
            </div>
            <% end %>
            </a>
            <a data-method="delete" href="/users/sign_out">
            <div class="col-lg-3 menu_content_container3">
              <p class="menu_content menu_3">
              <i class="fas fa-power-off"></i> Bye!
              </p>
            </div>
            </a>
          </div>
        </div>

        <div class="col-lg-2">
          <div class="logo_container center-block">
            <a href="#">
             <p class="logo_font text-center"><i class="fas fa-flag-checkered fa-2x"></i></p>
            </a>
          </div>
        </div>

        <div class="col-lg-5">
          <div class="row">
            <div class="col-lg-offset-7 col-lg-1">
              <a href="#">
              <%= link_to user_path(current_user.id) do %>
              <div class="header_profile_circle_wrapper">
                <%= attachment_image_tag current_user, :profile_image, :fill, 40, 40, class: "header_profile_circle", fallback:"no-image.jpg" %>
              </div>
              <% end %>
              </a>
            </div>
            <div class="col-lg-offset-1 col-lg-2 menu_content_container4_wrapper">
            <a href="/posts/new">
              <div class="menu_content_container4">
                <p class="menu_4">つぶやく</p>
              </div>
            </a>
            </div>
          </div>
        </div>
      </div>

    <% else %>

      <div class="row">
        <div class="col-lg-offset-1 col-lg-4">
          <div class="row">
            <a href="#">
            <div class="col-lg-4">
              <p class="menu_content menu_hover">
                Tsubuyakiとは？
              </p>
            </div>
            </a>
          </div>
        </div>

        <div class="col-lg-2">
          <div class="logo_container center-block">
            <a href="#">
             <p class="logo_font text-center"><i class="fas fa-flag-checkered fa-2x"></i></p>
            </a>
          </div>
        </div>

        <div class="col-lg-5">
          <div class="row">
            <a href="/users/sign_in">
            <div class="col-lg-offset-6 col-lg-2">
              <p class="menu_content menu_hover">ログイン</p>
            </div>
            </a>
            <a href="/users/sign_up">
            <div class="col-lg-offset-1 col-lg-2 menu_content_container4_wrapper">
              <div class="menu_content_container4">
                <p class="menu_4">SignUp</p>
              </div>
            </div>
            </a>
          </div>
        </div>
      </div>
    <% end %>

  	</header>
    <%= yield %>
  </body>

</html>

app/views/posts/edit.html.erb
<div class="background-container-small">
	<div class="tweet-detail">
		<div class="row">
			<div class='col-lg-offset-3 col-lg-6'>
				<div class="panel panel-default">
					<div class="panel-body">
						<span class="show_user_name">
							&emsp;Tsubuyakiの編集画面
						</span>
						<p><br></p>
						<div class="edit_form_container">
							<%= form_for(@post) do |f| %>
							<div class="row">
								<div class="col-lg-offset-1 col-lg-10">
									<%= f.text_area :content, class:"form-control" %>
								</div>
							</div>
							<p><br></p>
							<div class="row">
								<div class="col-lg-offset-10">
									<%= f.submit '編集完了', class: "btn btn-twitter-color btn-xs" %>
								<% end %>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<div class="background-container">
	<% flash.each do |name, msg| %>
	<div class="alert alert-<%= name %>">
		<a class="close" data-dismiss="alert">×</a>
	 	<%= msg %>
	</div>
	<% end %>
	<div class="row">
		<div class='col-lg-offset-1 col-lg-3'>
			<span>  <br> </span>
			<div class="panel panel-default">
			 <div class="panel-body">
			  	<div class="row index_profile_wrapper">
			  		<%= attachment_image_tag @user, :profile_image, :fill, 80, 80, class: "indext_image_circle", fallback:"no-image.jpg" %>
					<span class="current_user_name"> &emsp;<%= current_user.name %></span>
				</div>
				<span><br> </span>
				<div class="row">
			 		<div class='col-lg-4'>
			 			<p class="counter-title">つぶやき</p><br>
			 			<p class="counter-number">
			 			 <%= @counta.count %>
			 			</p>
			 		</div>
			 		<div class='col-lg-4'>
			 			<p class="counter-title">お気に入り</p><br>
			 			<p class="counter-number"><%= @countb.count %></p>
			 		</div>
			 		<div class='col-lg-4'>
			 			<p class="counter-title">ユーザー数</p><br>
			 			<p class="counter-number"><%= @users.count %></p>
			 		</div>
			  	</div>
			<hr>

			<p class="new_post_title">新しいつぶやき</p>
			 <div class="form-group">
				<%= form_for(@post) do |f| %>
				<%= f.text_area :content, :maxlength=>"140", class:"form-control", placeholder:"なにしてるなう？" %>
				<span><br></span>
				<%= f.submit 'つぶやく', class: "btn btn-twitter-color btn-xs" %>
				<% end %>
			  </div>
			 </div>
			</div>

			<div class="panel panel-default">
				<div class="panel-body">
			  	 <p class="ad_title">おすすめ</p>
			  	 <br>
			  	 <p class="ad_content">誰か広告出しませんか？「つぶやき」なら、広告掲載料0円です。</p>
			  	</div>
			</div>
		</div>

		<div class='col-lg-5'>
			<span> <br></span>

			<% @posts.each do |post| %>
			<div class="panel panel-default">
			 	<div class="panel-body">
			 	 <div class="panel-link">
			 	 	<div class="row">
			 	 		<div class="col-lg-2">
			 	 				<%= attachment_image_tag post.user, :profile_image, :fill, 40, 40, class: "index_post_user_photo", fallback:"no-image.jpg" %>
			 	 		</div>
			 	 		<div class="col-lg-6">
				 			<span class="tweet_user_name">
				 	  		<%= post.user.name %>
				 			</span>
				 		</div>
				 	</div>
				 	<br><br>
				 	<span class="tweet_content">&emsp;
					  <%= post.content %>
					</span>
				<hr>
				 <a href="#"><%= link_to post_path(post.id) do %>
				 	<% end %>
				 </a>
				 </div>
					<div class="row">
						<div class="col-lg-offset-7 col-lg-1">
							<a href ="#">
							  <%= link_to post_path(post.id), method: :get do %>
							  <i class="fas fa-info-circle my-blue show_link"></i>
							  <% end %>
							</a>
						</div>
						<div class='col-lg-offset-1 col-lg-1'>

						<% if post.favorited_by?(current_user)%>
						 <a href="#">
							<%= link_to post_favorites_path(post.id), method: :delete do %>
							<i class="fas fa-star my-yellow"></i>
							<% end %>
						 </a>
						<% else %>
						 <a href="#">
						 	<%= link_to post_favorites_path(post.id), method: :post do %>
						 	<i class="far fa-star my-gray star_blink"></i>
						 	<% end %>
						 <% end %>

						</div>
					</div>
			 	</div>
			</div>
			<% end %>
		</div>

		<div class='col-lg-3'>
			<span><br></span>
			<div class="panel_width">
				<div class="panel panel-default">
				 <div class="panel-body">
				 	<p class="index_user_title">現在のユーザー&emsp;<i class="fas fa-users"></i>
					</p>
					<br>

					<% @users.each do |user| %>
					 <div class="panel-link">
				 		<div class="index_user_name_container">
				 		<br>
				 			<div class="row">
				 			<div class="col-lg-2">
				 				<div class="index_user_photo">
				 					<%= attachment_image_tag user, :profile_image, :fill, 5, 5, class: "index_user_photo_circle", fallback:"no-image.jpg" %>
				 				</div>
				 			</div>
				 			<div class="col-lg-10">
				 				<p class="index_user_name">
								&emsp;<%= user.name %>
				 				</p>
				 			</div>
				 			</div>
				 		</div>
				 		<a href="#"><%= link_to user_path(user.id) do %>
				 		<% end %>
				 		</a>
				 	 </div>
				 	<% end %>
				 </div>
				</div>
			</div>
			<div class="panel_width">
				<div class="panel panel-default">
				 <div class="panel-body">
					<span class="copyright">Tsubuyakiについて<br>ヘルプセンター<br>規約<br>プライバシーポリシー<br>クッキー<br>広告について<br>Copyright © 2018 Masaru Miyachi All Rights Reserved.</span>
				 </div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/posts/new.html.erb
<div class="background-container-small">
	<div class="row">
		<div class="col-lg-offset-3 col-lg-6">
			<h1><br></h1>
			<div class="row">
			<div class="col-lg-12">
				<div class="new_tsubuyaki_submit_container">
			 	 <div class="new_tsubuyaki_submit_title_container">
			 	 	<p class="new_tsubuyaki_submit_title">新しいつぶやき</p>
			 	 </div>
			 	 <div class="new_tsubuyaki_submit_body_container">
			 	 	<div class="row">
			 	 	<div class="col-lg-offset-2 col-lg-8">
			 	 		<div class="form-group">
						 <%= form_for(@post) do |f| %>
						<div class="form_container">
						 <%= f.text_area :content, :maxlength=>"140", class:"form-control", placeholder:"なにしてるなう？" %>
						</div>
						<br>
						<div class="row">
						<div class="col-lg-offset-11">
						 <%= f.submit 'つぶやく',class: "btn btn-twitter-color btn-xs" %>
						 <% end %>
						</div>
						</div>
						</div>
					</div>
					</div>
				 </div>
				</div>
			</div>
			</div>
		</div>
	 </div>

	 <div class="col-lg-3">
	 </div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="background-container-small">
	<% flash.each do |name, msg| %>
	<div class="alert alert-<%= name %>">
		<a class="close" data-dismiss="alert">×</a>
	    <%= msg %>
	</div>
	<% end %>

	<div class="tweet-detail">
	  <div class="row">
		<div class='col-lg-offset-3 col-lg-6'>
			<div class="panel panel-default">
				<div class="panel-body">
					<div class="row">
						<div class="col-lg-1">
							<div class="show_post_image_circle_wrapper">
								<%= attachment_image_tag @user, :profile_image, :fill, 50, 50, class: "show_post_image_circle", fallback:"no-image.jpg" %>
							</div>
						</div>
						<div class="col-lg-10">
					 		<span class="show_user_name">
					 		&emsp;
				 	 		<%= @user.name %>
				 	 		</span>
				 	 	</div>
				 	</div>
				 	 <div class="row">
				 	 	<span><br></span>
				 	 </div>
				 	 <div class="show_tweet_content">
				 	 	&emsp;
					 	 <%= @post.content %>
				 	 </div>
				 	 	<span><br></span>
				 	 	<hr>
				 	 <div class="row">

				 	 <% if @post.favorited_by?(current_user) %>
				 	  <div class="col-lg-offset-8 col-lg-1">
				 	  	<a href="#">
				 	  		<%= link_to post_favorites_path(@post), method: :delete do %>
				 	  		<i class="fas fa-star my-yellow"></i>
				 	  		<% end %>
				 	  	</a>
				 	  </div>
				 	  		<% else %>
				 	  <div class="col-lg-offset-8 col-lg-1">
				 	  	<a href="#">
				 	  		<%= link_to post_favorites_path(@post), method: :post do %>
				 	  		<i class="far fa-star my-gray star_blink"></i>
				 	  		<% end %>
				 	  	</a>
				 	  </div>
				 	  <% end %>

				 	  <% if @post.user == current_user %>
				 	  <div class="col-lg-1">
				 	  	<a href="#">
				 		 	<%= link_to post_path(@post), method: :delete do %>
				 		 	<i class="far fa-trash-alt my-gray trash-can-blink"></i>
				 		 	<% end %>
				 		</a>
				 	  </div>
				 	  <div class="col-lg-1">
				 	  	<a href="#">
				 	  		<%= link_to edit_post_path(@post) do %>
				 	  		<i class="far fa-edit my-gray edit-blink"></i>
				 	 		<% end %>
				 	 	</a>
				 	 </div>
				 	 <% end %>
				 	 </div>
				</div>
			</div>
		</div>
	  </div>
	</div>
</div>

app/views/users/edit.html.erb
<div class="background-container">
	<br>
	<div class="row">
		<div class="col-lg-offset-1 col-lg-10">
			<p class="users_edit_title">プロフィールを編集</p>
		</div>
	</div>
	<br>
	<div class="row">
		<div class="col-lg-offset-2 col-lg-8">
			<div class="panel panel-default">
			<div class="panel-body">
				<br>
				<div class="row users_show_form">
					<div class="col-lg-offset-2 col-lg-8">
					<div class="form-group has-icon">


						<%= form_for(@user) do |f| %>
						<div class="user_edit_image">
							<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, class: "user_edit_image_circle" %>
						</div>
						<br>
						<label for="inputEmail">アイコン画像：</label>
						<%= f.attachment_field :profile_image, placeholder:"プロフィール画像" %>

					<br>
						<%= f.label :name, 'ユーザー名：' %>
						<%= f.text_field :name,  class:"form-control" %>
					<br>
						<%= f.label :profile, 'プロフィール：' %>
						<%= f.text_area :profile, class:"form-control" %>
					<br>
					<br>

					<div class="row">
						<div class="col-lg-offset-8 col-lg-4">
							<%= f.submit '変更を保存', class:"btn btn-default btn-block custom-1" %>
						</div>
					</div>
						<% end %>

					</div>
			 		</div>
				</div>
				<hr>
				<div class="row">
					<div class="col-lg-offset-2 col-lg-4">
						<p class="user_show_tsubuyaki_count_title">つぶやき</p>
					</div>
					<div class="col-lg-4">
						<p class="user_show_tsubuyaki_count_title">お気に入り</p>
					</div>
	 			</div>
				<div class="row">
					<div class="col-lg-offset-2 col-lg-4">
						<p class="user_show_tsubuyaki_count"><%= @posts.count %> </p>
					</div>
					<div class="col-lg-4">
						<p class="user_show_tsubuyaki_count"><%= @favorites.count %></p>
					</div>
				</div>
			</div>
			</div>
		<span class="user_show_tsubuyaki_title">過去のつぶやき</span>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-offset-3 col-lg-6">
			<p class="users_show_new_title"> New</p>
			<!-- ここから繰り返し -->
			<% @posts.each do |post| %>
			<div class="users_show_tsubuyaki_content_container">
				<div class="panel-link">
				 <div class="panel panel-default users_show_tsubuyaki_content_frame">
					<div class="panel-body users_show_tsubuyaki_content">
						<p class="users_show_tsubuyaki_content_letter">
						&emsp;<%= post.content %></p>
					</div>
					<a href="#"><%= link_to post_path(post.id) do %>
					<% end %>
					</a>
				 </div>
				</div>
					<div class="users_show_tsubuyaki_content_bar">
					</div>
			</div>
			<% end %>
			<!-- ここまでを繰り返し -->
				<div class="circle">
					<a class="circle-font" href="/posts/new">
					<p class="circle-font">Start</p>
					</a>
				</div>
			<br>
			<br>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="background-container">
	<br>
	<div class="row">
	<div class="col-lg-offset-2 col-lg-8">
		<div class="panel panel-default">
			<div class="panel-body">
			 <div class="row user_show_head_frame">
			 	<div class="col-lg-1">
			 		<div class="show_users_image_circle_wrapper">
			 			<%= attachment_image_tag @user, :profile_image, :fill, 80, 80, class: "show_users_image_circle", fallback:"no-image.jpg" %>
			 		</div>
			 		</a>
			 	</div>
				<div class="col-lg-5">
				<span class="user_show_user_name">&emsp;<%= @user.name %></span>
				</div>
				<% if params[:id].to_i == current_user.id %>
				<div class="col-lg-offset-3 col-lg-3">
					<a href="#">
					<%= link_to edit_user_path(params[:id]) do %>
					<div class="user_show_profile_edit_wrapper">
					<p class="user_show_profile_edit">プロフィールを編集</p>
					</div>
					<% end %>
					</a>
				</div>
				<% end %>
			 </div>
				<br><br>
				<div class="row">
					<div class="col-lg-offset-1 col-lg-9 user_show_profile">
						<p class="user_show_profile_content">
							&emsp;<%= @user.profile ||= "まだプロフィールを設定していないみたいです！" %>
						</p>
					</div>
				</div>
				<hr>
				<div class="row">
					<div class="col-lg-offset-2 col-lg-4">
						<p class="user_show_tsubuyaki_count_title">つぶやき</p>
					</div>
					<div class="col-lg-4">
						<p class="user_show_tsubuyaki_count_title">お気に入り</p>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-offset-2 col-lg-4">
						<p class="user_show_tsubuyaki_count"><%= @posts.count %> </p>
					</div>
					<div class="col-lg-4">
						<p class="user_show_tsubuyaki_count"><%= @favorites.count %></p>
					</div>
				</div>
			</div>
		</div>
		<span class="user_show_tsubuyaki_title">過去のつぶやき</span>
	</div>
	</div>

	<div class="row">
		<div class="col-lg-offset-3 col-lg-6">
			<p class="users_show_new_title"> New</p>
			<!-- ここから繰り返し -->
			<% @posts.each do |post| %>
			<div class="users_show_tsubuyaki_content_container">
				<div class="panel-link">
				 <div class="panel panel-default users_show_tsubuyaki_content_frame">
					<div class="panel-body users_show_tsubuyaki_content">
						<p class="users_show_tsubuyaki_content_letter">
						&emsp;<%= post.content %></p>
					</div>
					<a href="#"><%= link_to post_path(post.id) do %>
					<% end %>
					</a>
				 </div>
				</div>
					<div class="users_show_tsubuyaki_content_bar">
					</div>
			</div>
			<% end %>
			<!-- ここまでを繰り返し -->
				<div class="circle">
					<a class="circle-font" href="/posts/new">
					<p class="circle-font">Start</p>
					</a>
				</div>
			<br>
			<br>
		</div>
	</div>
</div>